cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('cart-add/', views.cart_add, name='cart-add'),
    path('cart-change/', views.cart_change, name='cart-change'),
    path('cart-remove/', views.cart_remove, name='cart-remove'),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

gradwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from gradwork import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('generate-photo/', views.gen_photo, name='gen_photo'),
    path('generate-image/', views.generate_image, name='generate_image'),  # Добавьте эту строку
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-cart/', views.users_cart, name='users-cart'),
    path('logout/', views.logout, name='logout')
]

templates/base.html
{% load static %}
{% load goods_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <!-- Стиль footer-a для главной страницы -->
    {% block css %}{% endblock %}
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static "deps/images/favicon.ico" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-success-subtle">
            <div class="container-fluid ms-4 me-3">
                <div class="d-inline-flex">
                    <img class="mx-2" src="{% static "deps/images/logo.png" %}" alt="logo" width="55" height="40">
                    <a class="navbar-brand fw-bold text-success-emphasis" href="{% url "main:index" %}">FlowerAI</a>
                    {% if user.is_authenticated %}
                        <div class="d-inline-flex">
                            <form class="d-flex me-auto" role="search" action="{% url "catalog:search" %}" method="get">
                                <input class="form-control me-2" type="search" name="q" placeholder="Поиск" aria-label="Search">
                                <button class="btn btn-success text-white" type="submit">Поиск</button>
                            </form>
                        </div>
                    {% endif %}
                </div>
                <div class="d-inline-flex">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-success" href="{% url "main:about" %}">Информация</a>
                            </li>
                            {% if not user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link text-success" href="{% url "user:login" %}">Войти</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link text-success" href="{% url "user:users-cart" %}">Корзина</a>
                                </li>
                                <li>
                                    <a class="nav-link" href="{% url "user:profile" %}">
                                        <img class="rounded-circle article-img ms-3" src="{{ request.user.image.url }}" width="30" height="30">
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <section>
        {% if user.is_authenticated %}
            <div class="container-fluid ms-5">
                <!-- Каталог и корзина с фиксированным расположением на странице -->
                <div class="row mt-5 position-absolute">
                    <!-- Каталог -->
                    <div class="dropdown mb-2">
                        <button class="btn btn-secondary dropdown-toggle btn-success" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Каталог
                            <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                                height="16">
                        </button>
                        <ul class="dropdown-menu" data-bs-theme="light">
                            {% tag_categories as categories %}
                            {% for category in categories %}
                                <li><a class="dropdown-item text-success" href="{% url "catalog:index" category.slug %}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- Значок корзины, вызывает модальное окно -->
                    {% block modal_cart %}{% endblock modal_cart %}
                    <!-- Закончилась разметка модального окна -->
                </div>
            </div>
        {% endif %}
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% include "includes/notifications.html" %}
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %}{% endblock %}
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
    {% block js %}{% endblock %}
</body>

</html>